'use client';

export type Language = 'id' | 'en';

export const SUPPORTED_LANGUAGES: { value: Language; label: string; flag: string }[] = [
  { value: 'id', label: 'Indonesia', flag: '🇮🇩' },
  { value: 'en', label: 'English', flag: '🇬🇧' },
];

export const translations = {
  id: {
    // ── Navbar ──
    profileTitle: 'Profil Raja',
    language: 'Bahasa',
    // ── Sidebar ──
    menu: 'Menu',
    navigation: 'Navigasi',
    recentSessions: 'Sesi Terbaru',
    currentSession: 'Sidang Saat Ini',
    sessionHistory: 'Riwayat Sidang',
    kingProfile: 'Profil Raja',
    settings: 'Pengaturan',
    openSidebar: 'Buka Sidebar',
    closeSidebar: 'Tutup Sidebar',
    // ── Route labels ──
    routeHome: 'Sidang Saat Ini',
    routeSessionHistory: 'Riwayat Sidang',
    routeProfile: 'Profil Raja',
    routeSettings: 'Pengaturan',
    routeDashboard: 'Dashboard',
    // ── Dashboard / Council ──
    dashboard: 'Dashboard',
    welcomeMessage: 'Selamat datang di KING DECISION. Ajukan ide Anda kepada Dewan.',
    waitingStatus: 'Menunggu titah Raja',
    // ── Transcript Panel ──
    transcript: 'Transkrip',
    transcriptTitle: 'Transkrip Sidang',
    searchTranscript: 'Cari transkrip...',
    searchPlaceholder: 'Cari pesan...',
    pinnedOnly: 'Pin saja',
    showPinnedOnly: 'Tampilkan pesan dipin',
    pinMessage: 'Pin pesan ini',
    unpinMessage: 'Lepas pin',
    noPinnedMessages: 'Belum ada pesan dipin',
    noSearchResults: 'Tidak ada hasil pencarian',
    statusActive: 'Aktif',
    statusStandby: 'Standby',
    statusDone: 'Selesai',
    messages: 'pesan',
    pinned: 'dipin',
    // ── Composer ──
    sendMessage: 'Kirim pesan...',
    startDebate: 'Mulai Sidang',
    stopDebate: 'Hentikan Sidang',
    callMinister: '📣 PANGGIL MENTERI:',
    clickToGreet: 'Klik untuk menyapa menteri',
    dragDropFiles: 'Seret & lepas file di sini, atau',
    browseFiles: 'pilih file',
    attachedFiles: 'File terlampir',
    removeFile: 'Hapus file',
    sendBtn: 'Kirim',
    // ── Council Verdict ──
    verdictCouncil: 'Verdik Dewan',
    verdictConclusion: 'Kesimpulan',
    verdictRisk: 'Risiko',
    verdictOpportunity: 'Peluang',
    verdictRecommendation: 'Rekomendasi',
    kingDecision: 'Keputusan Raja',
    approveDecision: '✓ Setujui',
    changeDirection: '↩ Ubah Arah',
    continueDebate: '⟳ Lanjutkan Debat',
    decisionMade: 'Keputusan telah diambil ♛',
    // ── Profile ──
    profile: 'Profil',
    editProfile: 'Edit Profil',
    setupProfile: 'Setup Profil',
    fullName: 'Nama Lengkap',
    fullNamePlaceholder: 'Masukkan nama lengkap Anda',
    username: 'Username',
    usernamePlaceholder: 'username_anda',
    email: 'Email',
    emailPlaceholder: 'email@contoh.com',
    phone: 'Nomor Telepon',
    phonePlaceholder: '+62 8xx xxxx xxxx',
    saveProfile: 'Simpan Profil',
    profileSaved: 'Profil Tersimpan',
    backToDashboard: 'Kembali',
    genderTitle: 'Gelar / Jenis Kelamin',
    royalTitle: 'Nama Panggilan Kerajaan',
    selectTitle: 'Pilih panggilan...',
    addCustom: 'Tambah Custom',
    customTitlePlaceholder: 'Ketik panggilan custom...',
    aiGreetingPreview: 'Pratinjau Sapaan AI',
    themeDisplay: 'Tema Tampilan',
    profileDataNote: 'Data profil disimpan di perangkat ini. AI akan menggunakan sapaan ini di seluruh sesi sidang.',
    // Onboarding
    welcomeTitle: 'Selamat Datang!',
    welcomeSubtitle: 'Anda baru pertama kali masuk ke Ruang Sidang Kerajaan',
    step1of3: 'Langkah 1 dari 3',
    step2of3: 'Langkah 2 dari 3 — Isi Profil',
    doneStep: 'Selesai ✓',
    beforeSessionStarts: 'Sebelum sidang dimulai...',
    beforeSessionDesc: 'Kami perlu mengenal Anda terlebih dahulu. AI akan menggunakan nama dan sapaan Anda di setiap sesi sidang.',
    startProfileSetup: 'Mulai Pengaturan Profil',
    skipForNow: 'Lewati untuk sekarang →',
    skip: 'Lewati →',
    setupInitial: '🚀 Setup Awal',
    introduceYourself: 'Kenalkan Diri Anda',
    introduceDesc: 'Data ini digunakan AI untuk memanggil Anda dengan sapaan yang tepat',
    profileReady: 'Profil Siap!',
    welcomeUser: 'Selamat datang',
    aiWillCall: 'AI akan memanggil Anda sebagai',
    inEachSession: 'di setiap sesi sidang. Anda bisa mengubah profil kapan saja lewat tombol profil di navbar.',
    enterDashboard: 'Masuk ke Dashboard',
    editProfileBadge: 'Edit Profil',
    myProfile: 'Profil Saya',
    myProfileDesc: 'Ubah nama, sapaan, dan preferensi tampilan Anda',
    // ── Settings ──
    settingsTitle: 'Pengaturan',
    settingsSubtitle: 'Konfigurasi KING DECISION',
    saveAll: 'Simpan Semua',
    saving: 'Menyimpan...',
    // Settings tabs
    tabWorkspace: 'Ruang Kerja',
    tabAiConfig: 'Konfigurasi AI',
    tabAudio: 'Audio & Notifikasi',
    tabApiKeys: 'API Keys',
    tabAbout: 'Tentang Aplikasi',
    // Workspace tab
    workspaceTitle: 'Ruang Kerja',
    workspaceDesc: 'Pengaturan umum untuk sesi sidang Anda',
    sectionSessionStorage: 'Sesi & Penyimpanan',
    autoSave: 'Simpan Otomatis',
    autoSaveDesc: 'Sesi akan disimpan secara otomatis setiap 5 menit',
    sessionNaming: 'Penamaan Sesi',
    sessionNamingDesc: 'Cara sesi baru diberi nama secara default',
    namingAuto: 'Otomatis dari topik',
    namingManual: 'Nama manual',
    namingDate: 'Berdasarkan tanggal',
    responseLanguage: 'Bahasa Respons',
    responseLanguageDesc: 'Bahasa yang digunakan menteri saat menjawab',
    langIndonesia: 'Bahasa Indonesia',
    langEnglish: 'English',
    langMixed: 'Mixed (ID + EN)',
    sectionDisplay: 'Tampilan & Animasi',
    ambientParticles: 'Partikel Ambient',
    ambientParticlesDesc: 'Efek partikel mengambang di latar belakang ruang sidang',
    tableAnimation: 'Animasi Meja',
    tableAnimationDesc: 'Efek animasi pada meja dan karakter menteri',
    sectionDataPrivacy: 'Data & Privasi',
    sectionDataPrivacySubtitle: 'Kelola data sesi dan riwayat sidang',
    saveHistory: 'Simpan Riwayat',
    saveHistoryDesc: 'Pertahankan riwayat sidang selama 90 hari',
    deleteAllHistory: 'Hapus Semua Riwayat',
    deleteAllHistoryDesc: 'Hapus permanen semua sesi yang tersimpan',
    deleteHistory: 'Hapus Riwayat',
    // AI Config tab
    aiConfigTitle: 'Konfigurasi AI',
    aiConfigDesc: 'Kelola karakter menteri, kepribadian, dan perilaku debat',
    aiCharacters: 'Karakter AI',
    aiCharactersDesc: 'Buat atau edit karakter menteri AI',
    createCharacter: 'Buat Karakter',
    builtIn: 'BAWAAN',
    editCharacter: 'Edit karakter',
    deleteCharacter: 'Hapus karakter',
    ministerPersonality: 'Kepribadian Menteri',
    autoModePersonality: 'Mode Auto — Kepribadian',
    autoModePersonalityDesc: 'Sistem menyeimbangkan kepribadian setiap menteri secara otomatis',
    customMode: 'Mode Custom',
    customModeDesc: 'Atur sendiri setiap parameter di bawah',
    autoModeActive: 'Mode Auto aktif — sistem menyeimbangkan kepribadian setiap menteri secara dinamis berdasarkan topik sidang.',
    personalityIntensity: 'Intensitas Kepribadian',
    personalityIntensityDesc: 'Seberapa kuat karakter dan opini menteri ini terasa',
    responseLength: 'Panjang Respons',
    responseLengthDesc: 'Tingkat detail dalam setiap respons menteri',
    opinionBoldness: 'Keberanian Berpendapat',
    opinionBoldnessDesc: 'Seberapa berani menteri menantang pendapat lain',
    debateBehavior: 'Perilaku Debat',
    autoModeDebate: 'Mode Auto — Debat',
    autoModeDebateDesc: 'Sistem mengatur ronde, intensitas, dan timing debat secara otomatis',
    autoModeDebateActive: 'Mode Auto aktif — sistem menyesuaikan ronde, intensitas, dan timing debat secara dinamis berdasarkan kompleksitas topik.',
    sectionDebateStructure: 'Struktur Debat',
    maxDebateRounds: 'Maksimum Ronde Debat',
    maxDebateRoundsDesc: 'Berapa ronde debat sebelum verdik otomatis dihasilkan',
    autoVerdict: 'Verdik Otomatis',
    autoVerdictDesc: 'Hasilkan verdik dewan secara otomatis setelah ronde selesai',
    allowDisagreement: 'Izinkan Ketidaksepakatan',
    allowDisagreementDesc: 'Menteri dapat saling bertentangan secara eksplisit',
    sectionTimingSpeed: 'Timing & Kecepatan',
    responseDelay: 'Jeda Antar Respons',
    debateIntensity: 'Intensitas Debat',
    sectionVerdictFormat: 'Format Verdik',
    showRisk: 'Tampilkan Risiko',
    showRiskDesc: 'Sertakan bagian risiko dalam setiap verdik dewan',
    showOpportunity: 'Tampilkan Peluang',
    showOpportunityDesc: 'Sertakan bagian peluang dalam setiap verdik dewan',
    showRecommendation: 'Tampilkan Rekomendasi Langkah',
    showRecommendationDesc: 'Sertakan rekomendasi konkret dan langkah tindakan',
    // Character form
    editCharacterTitle: 'Edit Karakter AI',
    createCharacterTitle: 'Buat Karakter AI Baru',
    characterName: 'Nama Karakter *',
    characterNamePlaceholder: 'cth: Grok, Qwen, Mistral...',
    characterRole: 'Peran / Jabatan',
    characterRolePlaceholder: 'cth: Menteri Strategi',
    characterProvider: 'Provider / Platform *',
    characterProviderPlaceholder: 'cth: xai, alibaba, mistral, openai...',
    characterProviderHint: 'Nama provider (huruf kecil). API key akan otomatis ditambahkan di tab API Keys.',
    characterModel: 'Nama Model *',
    characterModelPlaceholder: 'cth: grok-3, qwen-max, mistral-large...',
    characterDescription: 'Deskripsi',
    characterDescriptionPlaceholder: 'Deskripsi singkat karakter ini...',
    characterTraits: 'Sifat / Traits',
    characterTraitsPlaceholder: 'cth: Cepat, Efisien, Logis (pisahkan koma)',
    characterColor: 'Warna Karakter',
    characterPreview: 'Pratinjau',
    cancel: 'Batal',
    saveChanges: 'Simpan Perubahan',
    createCharacterBtn: 'Buat Karakter',
    // Audio tab
    audioTitle: 'Audio & Notifikasi',
    audioDesc: 'Pengaturan suara dan notifikasi sidang',
    sectionSound: 'Suara',
    soundEffects: 'Efek Suara',
    soundEffectsDesc: 'Aktifkan efek suara saat menteri berbicara dan transisi',
    ambientVolume: 'Volume Ambient',
    ambientVolumeDesc: 'Volume musik latar ruang sidang',
    sectionNotifications: 'Notifikasi',
    verdictNotification: 'Notifikasi Verdik',
    verdictNotificationDesc: 'Tampilkan notifikasi saat verdik dewan siap',
    debateDoneNotification: 'Notifikasi Debat Selesai',
    debateDoneNotificationDesc: 'Beritahu saat setiap ronde debat selesai',
    sectionAnimation: 'Animasi',
    animationSpeed: 'Kecepatan Animasi',
    reduceMotion: 'Kurangi Gerakan',
    reduceMotionDesc: 'Minimalkan animasi untuk kenyamanan visual',
    // API Keys tab
    apiKeysTitle: 'API Keys',
    apiKeysDesc: 'Masukkan API key untuk setiap model AI yang ingin digunakan',
    apiKeySecurity: 'Keamanan API Key',
    apiKeySecurityDesc: 'Key yang kamu masukkan akan disimpan terenkripsi di server dan tidak pernah dikembalikan ke browser. Setelah disimpan, key hanya ditampilkan dalam bentuk tersembunyi (••••).',
    apiKeyNever: 'tidak pernah',
    connected: 'Terhubung',
    notSet: 'Belum diset',
    updatedAt: 'Diperbarui',
    deleteKey: 'Hapus Key',
    saveAndLock: 'Simpan & Kunci',
    savingKey: 'Menyimpan...',
    customProvider: 'CUSTOM',
    apiKeyDevNote: 'Catatan developer: Fungsi penyimpanan di',
    apiKeyDevNoteEnd: 'sudah siap — tinggal ganti stub dengan Supabase call sesuai komentar di dalam file tersebut. Provider custom (dari karakter baru) otomatis muncul di sini.',
    // About tab
    aboutTitle: 'Tentang Aplikasi',
    aboutDesc: 'Informasi versi dan kredit',
    appTagline: 'Brainstorming bersama tiga menteri AI',
    appVersion: 'Versi 1.0.0 — Agustus 2026',
    sectionCouncil: 'Dewan Menteri',
    sectionTechnical: 'Teknis',
    ready: 'Siap',
    // ── Session History ──
    sessionHistoryTitle: 'Riwayat Sidang',
    sessionHistorySubtitle: 'Semua sesi brainstorming bersama Dewan Menteri AI',
    archiveBadge: '♛ Arsip KING DECISION',
    statTotalSessions: 'Total Sidang',
    statApproved: 'Disetujui',
    statChanged: 'Ubah Arah',
    statPending: 'Belum Selesai',
    searchSessions: 'Cari sidang...',
    filterAll: 'Semua',
    filterApproved: 'Disetujui',
    filterChanged: 'Ubah Arah',
    filterContinue: 'Debat Lanjut',
    filterPending: 'Belum Selesai',
    sortBy: 'Urutkan:',
    sortDate: 'Terbaru',
    sortRounds: 'Ronde Terbanyak',
    sortMessages: 'Pesan Terbanyak',
    resultsCount: 'dari',
    sessions: 'sidang',
    noSessionsFound: 'Tidak ada sidang ditemukan',
    noSessionsDesc: 'Coba ubah kata kunci pencarian atau filter untuk menemukan sidang yang Anda cari.',
    continueSession: 'Lanjutkan',
    roundsLabel: 'ronde',
  },
  en: {
    // ── Navbar ──
    profileTitle: 'King Profile',
    language: 'Language',
    // ── Sidebar ──
    menu: 'Menu',
    navigation: 'Navigation',
    recentSessions: 'Recent Sessions',
    currentSession: 'Current Session',
    sessionHistory: 'Session History',
    kingProfile: 'King Profile',
    settings: 'Settings',
    openSidebar: 'Open Sidebar',
    closeSidebar: 'Close Sidebar',
    // ── Route labels ──
    routeHome: 'Current Session',
    routeSessionHistory: 'Session History',
    routeProfile: 'King Profile',
    routeSettings: 'Settings',
    routeDashboard: 'Dashboard',
    // ── Dashboard / Council ──
    dashboard: 'Dashboard',
    welcomeMessage: 'Welcome to KING DECISION. Submit your idea to the Council.',
    waitingStatus: 'Awaiting the King\'s command',
    // ── Transcript Panel ──
    transcript: 'Transcript',
    transcriptTitle: 'Session Transcript',
    searchTranscript: 'Search transcript...',
    searchPlaceholder: 'Search messages...',
    pinnedOnly: 'Pinned only',
    showPinnedOnly: 'Show pinned messages',
    pinMessage: 'Pin this message',
    unpinMessage: 'Unpin',
    noPinnedMessages: 'No pinned messages yet',
    noSearchResults: 'No search results',
    statusActive: 'Active',
    statusStandby: 'Standby',
    statusDone: 'Done',
    messages: 'messages',
    pinned: 'pinned',
    // ── Composer ──
    sendMessage: 'Send a message...',
    startDebate: 'Start Session',
    stopDebate: 'Stop Session',
    callMinister: '📣 CALL MINISTER:',
    clickToGreet: 'Click to greet a minister',
    dragDropFiles: 'Drag & drop files here, or',
    browseFiles: 'browse files',
    attachedFiles: 'Attached files',
    removeFile: 'Remove file',
    sendBtn: 'Send',
    // ── Council Verdict ──
    verdictCouncil: 'Council Verdict',
    verdictConclusion: 'Conclusion',
    verdictRisk: 'Risk',
    verdictOpportunity: 'Opportunity',
    verdictRecommendation: 'Recommendation',
    kingDecision: 'King\'s Decision',
    approveDecision: '✓ Approve',
    changeDirection: '↩ Change Direction',
    continueDebate: '⟳ Continue Debate',
    decisionMade: 'Decision has been made ♛',
    // ── Profile ──
    profile: 'Profile',
    editProfile: 'Edit Profile',
    setupProfile: 'Setup Profile',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    username: 'Username',
    usernamePlaceholder: 'your_username',
    email: 'Email',
    emailPlaceholder: 'email@example.com',
    phone: 'Phone Number',
    phonePlaceholder: '+1 xxx xxx xxxx',
    saveProfile: 'Save Profile',
    profileSaved: 'Profile Saved',
    backToDashboard: 'Back',
    genderTitle: 'Title / Gender',
    royalTitle: 'Royal Title',
    selectTitle: 'Select title...',
    addCustom: 'Add Custom',
    customTitlePlaceholder: 'Type custom title...',
    aiGreetingPreview: 'AI Greeting Preview',
    themeDisplay: 'Display Theme',
    profileDataNote: 'Profile data is stored on this device. AI will use this greeting throughout all sessions.',
    // Onboarding
    welcomeTitle: 'Welcome!',
    welcomeSubtitle: 'You are entering the Royal Council Chamber for the first time',
    step1of3: 'Step 1 of 3',
    step2of3: 'Step 2 of 3 — Fill Profile',
    doneStep: 'Done ✓',
    beforeSessionStarts: 'Before the session begins...',
    beforeSessionDesc: 'We need to get to know you first. AI will use your name and title in every session.',
    startProfileSetup: 'Start Profile Setup',
    skipForNow: 'Skip for now →',
    skip: 'Skip →',
    setupInitial: '🚀 Initial Setup',
    introduceYourself: 'Introduce Yourself',
    introduceDesc: 'This data is used by AI to address you with the right title',
    profileReady: 'Profile Ready!',
    welcomeUser: 'Welcome',
    aiWillCall: 'AI will address you as',
    inEachSession: 'in every session. You can update your profile anytime via the profile button in the navbar.',
    enterDashboard: 'Enter Dashboard',
    editProfileBadge: 'Edit Profile',
    myProfile: 'My Profile',
    myProfileDesc: 'Change your name, title, and display preferences',
    // ── Settings ──
    settingsTitle: 'Settings',
    settingsSubtitle: 'Configure KING DECISION',
    saveAll: 'Save All',
    saving: 'Saving...',
    // Settings tabs
    tabWorkspace: 'Workspace',
    tabAiConfig: 'AI Config',
    tabAudio: 'Audio & Notifications',
    tabApiKeys: 'API Keys',
    tabAbout: 'About',
    // Workspace tab
    workspaceTitle: 'Workspace',
    workspaceDesc: 'General settings for your council sessions',
    sectionSessionStorage: 'Sessions & Storage',
    autoSave: 'Auto Save',
    autoSaveDesc: 'Sessions will be saved automatically every 5 minutes',
    sessionNaming: 'Session Naming',
    sessionNamingDesc: 'How new sessions are named by default',
    namingAuto: 'Auto from topic',
    namingManual: 'Manual name',
    namingDate: 'Based on date',
    responseLanguage: 'Response Language',
    responseLanguageDesc: 'Language used by ministers when responding',
    langIndonesia: 'Bahasa Indonesia',
    langEnglish: 'English',
    langMixed: 'Mixed (ID + EN)',
    sectionDisplay: 'Display & Animation',
    ambientParticles: 'Ambient Particles',
    ambientParticlesDesc: 'Floating particle effects in the council chamber background',
    tableAnimation: 'Table Animation',
    tableAnimationDesc: 'Animation effects on the table and minister characters',
    sectionDataPrivacy: 'Data & Privacy',
    sectionDataPrivacySubtitle: 'Manage session data and session history',
    saveHistory: 'Save History',
    saveHistoryDesc: 'Keep session history for 90 days',
    deleteAllHistory: 'Delete All History',
    deleteAllHistoryDesc: 'Permanently delete all saved sessions',
    deleteHistory: 'Delete History',
    // AI Config tab
    aiConfigTitle: 'AI Configuration',
    aiConfigDesc: 'Manage minister characters, personalities, and debate behavior',
    aiCharacters: 'AI Characters',
    aiCharactersDesc: 'Create or edit AI minister characters',
    createCharacter: 'Create Character',
    builtIn: 'BUILT-IN',
    editCharacter: 'Edit character',
    deleteCharacter: 'Delete character',
    ministerPersonality: 'Minister Personality',
    autoModePersonality: 'Auto Mode — Personality',
    autoModePersonalityDesc: 'System automatically balances each minister\'s personality',
    customMode: 'Custom Mode',
    customModeDesc: 'Manually adjust each parameter below',
    autoModeActive: 'Auto mode active — system dynamically balances each minister\'s personality based on the session topic.',
    personalityIntensity: 'Personality Intensity',
    personalityIntensityDesc: 'How strongly this minister\'s character and opinions come through',
    responseLength: 'Response Length',
    responseLengthDesc: 'Level of detail in each minister\'s response',
    opinionBoldness: 'Opinion Boldness',
    opinionBoldnessDesc: 'How boldly the minister challenges other opinions',
    debateBehavior: 'Debate Behavior',
    autoModeDebate: 'Auto Mode — Debate',
    autoModeDebateDesc: 'System automatically manages rounds, intensity, and debate timing',
    autoModeDebateActive: 'Auto mode active — system dynamically adjusts rounds, intensity, and debate timing based on topic complexity.',
    sectionDebateStructure: 'Debate Structure',
    maxDebateRounds: 'Maximum Debate Rounds',
    maxDebateRoundsDesc: 'How many rounds before an automatic verdict is generated',
    autoVerdict: 'Auto Verdict',
    autoVerdictDesc: 'Automatically generate council verdict after rounds complete',
    allowDisagreement: 'Allow Disagreement',
    allowDisagreementDesc: 'Ministers can explicitly contradict each other',
    sectionTimingSpeed: 'Timing & Speed',
    responseDelay: 'Response Delay',
    debateIntensity: 'Debate Intensity',
    sectionVerdictFormat: 'Verdict Format',
    showRisk: 'Show Risk',
    showRiskDesc: 'Include risk section in every council verdict',
    showOpportunity: 'Show Opportunity',
    showOpportunityDesc: 'Include opportunity section in every council verdict',
    showRecommendation: 'Show Action Recommendations',
    showRecommendationDesc: 'Include concrete recommendations and action steps',
    // Character form
    editCharacterTitle: 'Edit AI Character',
    createCharacterTitle: 'Create New AI Character',
    characterName: 'Character Name *',
    characterNamePlaceholder: 'e.g.: Grok, Qwen, Mistral...',
    characterRole: 'Role / Title',
    characterRolePlaceholder: 'e.g.: Strategy Minister',
    characterProvider: 'Provider / Platform *',
    characterProviderPlaceholder: 'e.g.: xai, alibaba, mistral, openai...',
    characterProviderHint: 'Provider name (lowercase). API key will be automatically added in the API Keys tab.',
    characterModel: 'Model Name *',
    characterModelPlaceholder: 'e.g.: grok-3, qwen-max, mistral-large...',
    characterDescription: 'Description',
    characterDescriptionPlaceholder: 'Brief description of this character...',
    characterTraits: 'Traits',
    characterTraitsPlaceholder: 'e.g.: Fast, Efficient, Logical (comma separated)',
    characterColor: 'Character Color',
    characterPreview: 'Preview',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    createCharacterBtn: 'Create Character',
    // Audio tab
    audioTitle: 'Audio & Notifications',
    audioDesc: 'Sound and notification settings for sessions',
    sectionSound: 'Sound',
    soundEffects: 'Sound Effects',
    soundEffectsDesc: 'Enable sound effects when ministers speak and during transitions',
    ambientVolume: 'Ambient Volume',
    ambientVolumeDesc: 'Background music volume for the council chamber',
    sectionNotifications: 'Notifications',
    verdictNotification: 'Verdict Notification',
    verdictNotificationDesc: 'Show notification when council verdict is ready',
    debateDoneNotification: 'Debate Round Done',
    debateDoneNotificationDesc: 'Notify when each debate round is complete',
    sectionAnimation: 'Animation',
    animationSpeed: 'Animation Speed',
    reduceMotion: 'Reduce Motion',
    reduceMotionDesc: 'Minimize animations for visual comfort',
    // API Keys tab
    apiKeysTitle: 'API Keys',
    apiKeysDesc: 'Enter API keys for each AI model you want to use',
    apiKeySecurity: 'API Key Security',
    apiKeySecurityDesc: 'Keys you enter are stored encrypted on the server and are never returned to the browser. Once saved, keys are only shown in masked form (••••).',
    apiKeyNever: 'never',
    connected: 'Connected',
    notSet: 'Not set',
    updatedAt: 'Updated',
    deleteKey: 'Delete Key',
    saveAndLock: 'Save & Lock',
    savingKey: 'Saving...',
    customProvider: 'CUSTOM',
    apiKeyDevNote: 'Developer note: The storage function in',
    apiKeyDevNoteEnd: 'is ready — just replace the stub with a Supabase call as noted in the comments. Custom providers (from new characters) appear here automatically.',
    // About tab
    aboutTitle: 'About',
    aboutDesc: 'Version information and credits',
    appTagline: 'Brainstorming with three AI ministers',
    appVersion: 'Version 1.0.0 — August 2026',
    sectionCouncil: 'Council Ministers',
    sectionTechnical: 'Technical',
    ready: 'Ready',
    // ── Session History ──
    sessionHistoryTitle: 'Session History',
    sessionHistorySubtitle: 'All brainstorming sessions with the AI Council',
    archiveBadge: '♛ KING DECISION Archive',
    statTotalSessions: 'Total Sessions',
    statApproved: 'Approved',
    statChanged: 'Changed',
    statPending: 'Incomplete',
    searchSessions: 'Search sessions...',
    filterAll: 'All',
    filterApproved: 'Approved',
    filterChanged: 'Changed',
    filterContinue: 'Debate Continues',
    filterPending: 'Incomplete',
    sortBy: 'Sort by:',
    sortDate: 'Latest',
    sortRounds: 'Most Rounds',
    sortMessages: 'Most Messages',
    resultsCount: 'of',
    sessions: 'sessions',
    noSessionsFound: 'No sessions found',
    noSessionsDesc: 'Try changing the search keyword or filter to find the session you\'re looking for.',
    continueSession: 'Continue',
    roundsLabel: 'rounds',
  },
} as const;

export type TranslationKey = keyof typeof translations.id;

export function getTranslations(lang: Language) {
  return translations[lang];
}

export function getStoredLanguage(): Language {
  if (typeof window === 'undefined') return 'id';
  return (localStorage.getItem('app-language') as Language) ?? 'id';
}

export function setStoredLanguage(lang: Language) {
  if (typeof window !== 'undefined') {
    localStorage.setItem('app-language', lang);
  }
}
